name: Create a comment on new issue

on:
  issue:
    types: [opened]

    jobs:
      comment-with-actions:
        runs-on: ubuntu-latest
        steps:
          - name: "dump github context"
            run: echo '${{ toJSON(github.event)}}'
            shell: bash
